# Generated by Django 5.2.9 on 2026-01-09 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Consulta original del usuario')),
                ('processed_query', models.TextField(blank=True, help_text='Consulta procesada/optimizada para búsqueda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de búsqueda',
                'verbose_name_plural': 'Consultas de búsqueda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='Mensaje del usuario')),
                ('assistant_response', models.TextField(help_text='Respuesta del asistente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
                ('search_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='assistant.searchquery')),
            ],
            options={
                'verbose_name': 'Historial de chat',
                'verbose_name_plural': 'Historial de chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del resultado', max_length=500)),
                ('url', models.URLField(help_text='URL de la fuente', max_length=2000)),
                ('snippet', models.TextField(help_text='Fragmento/resumen del contenido')),
                ('content', models.TextField(blank=True, help_text='Contenido extraído de la página')),
                ('position', models.PositiveIntegerField(help_text='Posición en los resultados (1, 2, 3...)')),
                ('relevance_score', models.FloatField(default=0.0, help_text='Puntuación de relevancia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assistant.searchquery')),
            ],
            options={
                'verbose_name': 'Resultado de búsqueda',
                'verbose_name_plural': 'Resultados de búsqueda',
                'ordering': ['position'],
                'unique_together': {('search_query', 'url')},
            },
        ),
    ]
